# DO-NOT-EDIT: Generated by github:vic/flake-file.
# To re-generate use: nix-shell . -A flake-file.sh --run write-inputs
{
  den.url = "github:denful/den";
  den-diagram.url = "github:denful/den-diagram";
  disko = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/disko";
  };
  flake-file.url = "github:denful/flake-file";
  flake-parts = {
    inputs.nixpkgs-lib.follows = "nixpkgs";
    url = "github:hercules-ci/flake-parts";
  };
  home-manager = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/home-manager/release-26.05";
  };
  import-tree.url = "github:vic/import-tree";
  lem = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:lem-project/lem";
  };
  nix-doom-emacs-unstraightened = {
    inputs.nixpkgs.follows = "";
    url = "github:marienz/nix-doom-emacs-unstraightened";
  };
  nixos-hardware = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:NixOS/nixos-hardware";
  };
  nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
  nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
  nur = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/NUR";
  };
  zed-extensions.url = "github:DuskSystems/nix-zed-extensions";
}
