;; THIS IS AN AUTOGENERATED FILE, DO NOT EDIT
;;
;; S-Expressions in this file are not evaluated,
;; Lisp code meant to be evalated should be put in the file `init.lisp` instead.

(:COLOR-THEME "gruvbox-dark-pale")